# Generated by Django 2.2.4 on 2021-05-30 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_books', to='first_django_app.User')),
                ('users', models.ManyToManyField(related_name='books', to='first_django_app.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
