# Generated by Django 2.2.4 on 2021-05-30 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_django_app', '0003_auto_20210530_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='uploaded_by_id',
            new_name='uploader',
        ),
    ]
