# Generated by Django 2.2.4 on 2021-05-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
